#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("InsideInning.Droid.Resource", IsApplication=true)]

namespace InsideInning.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010001
			public const int state_current_month = 2130771969;
			
			// aapt resource value: 0x7f010006
			public const int state_highlighted = 2130771974;
			
			// aapt resource value: 0x7f010003
			public const int state_range_first = 2130771971;
			
			// aapt resource value: 0x7f010005
			public const int state_range_last = 2130771973;
			
			// aapt resource value: 0x7f010004
			public const int state_range_middle = 2130771972;
			
			// aapt resource value: 0x7f010000
			public const int state_selectable = 2130771968;
			
			// aapt resource value: 0x7f010002
			public const int state_today = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int calendar_active_month_bg = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int calendar_bg = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int calendar_divider = 2130968578;
			
			// aapt resource value: 0x7f040005
			public const int calendar_highlighted_day_bg = 2130968581;
			
			// aapt resource value: 0x7f040003
			public const int calendar_inactive_month_bg = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int calendar_selected_day_bg = 2130968580;
			
			// aapt resource value: 0x7f040006
			public const int calendar_selected_range_bg = 2130968582;
			
			// aapt resource value: 0x7f040008
			public const int calendar_text_active = 2130968584;
			
			// aapt resource value: 0x7f040007
			public const int calendar_text_inactive = 2130968583;
			
			// aapt resource value: 0x7f040009
			public const int calendar_text_selected = 2130968585;
			
			// aapt resource value: 0x7f04000b
			public const int calendar_text_selector = 2130968587;
			
			// aapt resource value: 0x7f04000a
			public const int calendar_text_unselectable = 2130968586;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050000
			public const int calendar_day_headers_paddingbottom = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int calendar_month_title_bottommargin = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int calendar_month_topmargin = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int calendar_text_medium = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int calendar_text_small = 2131034116;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int about = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int AmanWalia = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int AnilSethi = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int back = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int backO = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int balance = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Balance128 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int BhavnaPruthi = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int birthday = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int blog = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int Calendar = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int Calendar128 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int calendar_bg_selector = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int contact = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int cover = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int desig = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int email = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int Employee128 = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int GagandeepSingh = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int ic_launcher = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int Icon = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int iiTabBox = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int iiTextBox = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int KetanSharma = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int leaves = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int LeftTopCorner = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int menuIcon = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int MohdRiyaz = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int NainaSharma = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int NehaGupta = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int NotePad = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int NotePad128 = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int Notes = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int notify = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int Notify128 = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int password = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int persons = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int refresh = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int RigthTopCorner = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int RupreetGujral = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int rzee = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int ShagunBawa = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int slideout = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int splash = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int summary = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int twitternav = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int Usrename = 2130837550;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080004
			public const int SplashImageView = 2131230724;
			
			// aapt resource value: 0x7f080003
			public const int TheSplashLayout = 2131230723;
			
			// aapt resource value: 0x7f080002
			public const int calendar_grid = 2131230722;
			
			// aapt resource value: 0x7f080000
			public const int calendar_view = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int title = 2131230721;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int calendar_picker = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int dialog = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int month = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int SplashScreen = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int week = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int day_name_format = 2131099649;
			
			// aapt resource value: 0x7f060004
			public const int full_date_format = 2131099652;
			
			// aapt resource value: 0x7f060002
			public const int invalid_date = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int library_name = 2131099648;
			
			// aapt resource value: 0x7f060003
			public const int month_name_format = 2131099651;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070001
			public const int CalendarCell = 2131165185;
			
			// aapt resource value: 0x7f070003
			public const int CalendarCell_CalendarDate = 2131165187;
			
			// aapt resource value: 0x7f070002
			public const int CalendarCell_DayHeader = 2131165186;
			
			// aapt resource value: 0x7f070000
			public const int CalendarTitle = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] calendar_cell = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974};
			
			// aapt resource value: 1
			public const int calendar_cell_state_current_month = 1;
			
			// aapt resource value: 6
			public const int calendar_cell_state_highlighted = 6;
			
			// aapt resource value: 3
			public const int calendar_cell_state_range_first = 3;
			
			// aapt resource value: 5
			public const int calendar_cell_state_range_last = 5;
			
			// aapt resource value: 4
			public const int calendar_cell_state_range_middle = 4;
			
			// aapt resource value: 0
			public const int calendar_cell_state_selectable = 0;
			
			// aapt resource value: 2
			public const int calendar_cell_state_today = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
